version: '3.8'

services:
  # Docker-In-Docker (DinD) service
  dind:
    image: docker:20.10.7-dind
    container_name: dind_container
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    volumes:
      - dind_storage:/var/lib/docker
    networks:
      - jenkins
    ports:
      - "2375:2375"  # Docker Daemon port (without TLS)

  # Jenkins service
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins_container
    privileged: true
    user: root
    environment:
      DOCKER_HOST: "tcp://dind:2375"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
    ports:
      - "8081:8080"
      - "50000:50000"
    networks:
      - jenkins

volumes:
  jenkins_home:  # Persistent storage for Jenkins data
  dind_storage:  # Persistent storage for Docker data inside DinD

networks:
  jenkins:
    driver: bridge
